import { motion } from "framer-motion";
import { AreaChart } from "../components/charts";
import { CountUp } from "../components/CountUp";
import { Avatar, agentTone, EmptyState } from "../components/ui";
import { useNow, useWorld } from "../data/source";
import { fmtUsd, timeAgo } from "../lib/format";

export function Pool() {
  const world = useWorld();
  const now = useNow(1000);
  const { pool } = world;
  const sharePrice = pool.shares > 0 ? pool.assets / pool.shares : 1;
  const byId = new Map(world.agents.map((a) => [a.id, a]));
  const premiums = world.events.filter((e) => e.kind === "settled").slice(0, 7);

  return (
    <div className="pool-grid">
      <motion.div className="card" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
        <p className="eyebrow">Underwriter pool</p>
        <div className="hero-num">
          <CountUp value={pool.assets} format={(v) => fmtUsd(v)} />
        </div>
        <div className="hero-sub">USDC backing the fleet's promises · {pool.lps} underwriters</div>

        <AreaChart points={pool.history} label="Pool assets over time" />

        <div className="pool-kpis">
          <div>
            <div className="k">Share price</div>
            <div className="v mono">
              <CountUp value={sharePrice} format={(v) => v.toFixed(4)} />
            </div>
          </div>
          <div>
            <div className="k">Premiums this session</div>
            <div className="v mono" style={{ color: "var(--green)" }}>
              <CountUp value={pool.premiumsSession} format={(v) => `+${fmtUsd(v)}`} />
            </div>
          </div>
          <div>
            <div className="k">Claims absorbed</div>
            <div className="v mono">
              <CountUp value={world.claimsCount} format={(v) => Math.round(v).toString()} />
            </div>
          </div>
        </div>
        <div className="footnote">
          Premiums from every settled job accrue to LP shares — yield generated by real work, not emissions.
        </div>
      </motion.div>

      <div className="stack">
        <motion.div className="card flat" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
          <p className="eyebrow">Earn</p>
          <h3 className="section-title" style={{ marginBottom: 10 }}>Provide coverage</h3>
          <div className="prose" style={{ marginBottom: 15 }}>
            Deposit USDC, receive pool shares, and earn the premium on every job the fleet settles. Co-signing bonds for
            agents that can't fully self-stake is next on the roadmap.
          </div>
          <button className="btn" style={{ width: "100%" }} disabled title="Enabled once contracts are live on Arc testnet">
            Deposit USDC — after testnet deploy
          </button>
        </motion.div>

        <motion.div className="card" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.18 }}>
          <div className="section-head">
            <h3 className="section-title">Recent premiums</h3>
            <span className="section-note">income</span>
          </div>
          {premiums.length === 0 ? (
            <EmptyState icon="＋" title="No premiums yet" sub="They land as jobs settle" />
          ) : (
            <div className="rows">
              {premiums.map((e) => {
                const a = byId.get(e.agentId);
                return (
                  <div key={e.id} className="row fleet-row">
                    <Avatar initial={a?.initial ?? "?"} tone={agentTone(e.agentId)} size={28} />
                    <div className="row-main">
                      <div className="fleet-name">{a?.name}</div>
                      <div className="fleet-meta">job #{e.jobId} · {timeAgo(e.at, now)}</div>
                    </div>
                    <div className="row-amt pos">+{fmtUsd(e.premium ?? 0)}</div>
                  </div>
                );
              })}
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
}
