import { motion } from "framer-motion";
import { AreaChart } from "../components/charts";
import { CountUp } from "../components/CountUp";
import { useNow, useWorld } from "../data/source";
import { fmtUsd, timeAgo } from "../lib/format";

export function Pool() {
  const world = useWorld();
  const now = useNow(1000);
  const { pool } = world;
  const sharePrice = pool.shares > 0 ? pool.assets / pool.shares : 1;
  const byId = new Map(world.agents.map((a) => [a.id, a]));
  const premiums = world.events.filter((e) => e.kind === "settled").slice(0, 6);

  return (
    <div className="pool-grid">
      <motion.div className="card pool-hero" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
        <p className="eyebrow">Underwriter pool</p>
        <div className="stat-value">
          <CountUp value={pool.assets} format={(v) => fmtUsd(v)} />
        </div>
        <div className="stat-sub">
          USDC backing the fleet's promises · {pool.lps} underwriters
        </div>
        <AreaChart points={pool.history} label="Pool assets over time" />
        <div className="footnote">
          Premiums from every settled job accrue to LP shares — yield generated by real work, not emissions.
        </div>

        <div className="pool-kpis">
          <div>
            <div className="stat-label">Share price</div>
            <div className="stat-value" style={{ fontSize: 22 }}>
              <CountUp value={sharePrice} format={(v) => v.toFixed(4)} />
            </div>
          </div>
          <div>
            <div className="stat-label">Premiums this session</div>
            <div className="stat-value" style={{ fontSize: 22, color: "var(--green)" }}>
              <CountUp value={pool.premiumsSession} format={(v) => `+${fmtUsd(v)}`} />
            </div>
          </div>
          <div>
            <div className="stat-label">Claims absorbed</div>
            <div className="stat-value" style={{ fontSize: 22 }}>
              <CountUp value={world.claimsCount} format={(v) => Math.round(v).toString()} />
            </div>
          </div>
        </div>
      </motion.div>

      <div className="stack">
        <motion.div className="card" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
          <p className="eyebrow">Earn</p>
          <h3 className="section-title">Provide coverage</h3>
          <div style={{ fontSize: 13.5, color: "var(--text-2)", lineHeight: 1.6, marginBottom: 14 }}>
            Deposit USDC, receive pool shares, and earn the premium on every job the fleet settles. Co-signing
            bonds for agents that can't fully self-stake is next on the roadmap.
          </div>
          <button className="btn" disabled title="Enabled once contracts are live on Arc testnet">
            Deposit USDC — after testnet deploy
          </button>
        </motion.div>

        <motion.div className="card" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.18 }}>
          <p className="eyebrow">Income</p>
          <h3 className="section-title">Recent premiums</h3>
          <div style={{ display: "grid", gap: 10 }}>
            {premiums.map((e) => (
              <div key={e.id} style={{ display: "flex", alignItems: "center", gap: 10, fontSize: 13 }}>
                <span className="badge green" aria-hidden="true">＋</span>
                <span style={{ color: "var(--text-2)" }}>
                  {byId.get(e.agentId)?.name} · job #{e.jobId}
                </span>
                <span className="mono" style={{ marginLeft: "auto", fontWeight: 640, color: "var(--green)" }}>
                  +{fmtUsd(e.premium ?? 0)}
                </span>
                <span style={{ fontSize: 11.5, color: "var(--text-3)", width: 64, textAlign: "right" }}>{timeAgo(e.at, now)}</span>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </div>
  );
}
