import type { AgentStats, Candidate, OfferView } from "@bonded/underwriting";
import { useCallback, useState } from "react";
import { loadChainSnapshot, type ChainSnapshot, type Settlement } from "./chainSource";
import manifest from "./proof.json";

/**
 * Data for the Proof view, in two tiers.
 *
 * The shipped manifest (`proof.json`, generated by `npm run snapshot`) loads
 * instantly and always works — settled jobs are immutable, and every entry
 * carries its transaction hash so anyone can verify it on ArcScan. Arc's
 * public RPC caps eth_getLogs at 10,000 blocks and rate-limits bursts, so a
 * page that scanned history live would be slow at best and dead on stage at
 * worst.
 *
 * "Refresh" then re-reads current state directly from Arc. The UI always says
 * which of the two it is showing — it never implies live data it doesn't have.
 */

export type Source = "snapshot" | "live";

export type ChainState = {
  snapshot: ChainSnapshot;
  source: Source;
  loading: boolean;
  error: string | null;
};

type RawManifest = typeof manifest;

/** JSON carries bigints as strings; restore them at the boundary. */
function hydrate(m: RawManifest): ChainSnapshot {
  const settlements: Settlement[] = m.settlements.map((s) => ({
    jobId: BigInt(s.jobId),
    passed: s.passed,
    primary: BigInt(s.primary),
    secondary: BigInt(s.secondary),
    price: BigInt(s.price),
    agent: s.agent as `0x${string}`,
    agentName: s.agentName,
    buyer: s.buyer as `0x${string}`,
    txHash: s.txHash as `0x${string}`,
    blockNumber: BigInt(s.blockNumber),
  }));

  const candidates: Candidate[] = m.candidates.map((c) => ({
    label: c.label,
    offer: {
      offerId: BigInt(c.offer.offerId),
      agent: c.offer.agent as `0x${string}`,
      price: BigInt(c.offer.price),
      bondSlice: BigInt(c.offer.bondSlice),
      premium: BigInt(c.offer.premium),
      deliveryWindow: c.offer.deliveryWindow,
      disputeWindow: c.offer.disputeWindow,
      checker: c.offer.checker as `0x${string}`,
      criteriaHash: c.offer.criteriaHash as `0x${string}`,
      uri: c.offer.uri,
      active: c.offer.active,
    } satisfies OfferView,
    stats: {
      staked: BigInt(c.stats.staked),
      locked: BigInt(c.stats.locked),
      available: BigInt(c.stats.available),
      jobs: c.stats.jobs,
      passed: c.stats.passed,
      failed: c.stats.failed,
      volumePaid: BigInt(c.stats.volumePaid),
      volumeSlashed: BigInt(c.stats.volumeSlashed),
    } satisfies AgentStats,
  }));

  return {
    settlements,
    candidates,
    poolAssets: BigInt(m.poolAssets),
    totalBonded: BigInt(m.totalBonded),
    blockNumber: BigInt(m.blockNumber),
    fetchedAt: new Date(m.generatedAt).getTime(),
  };
}

const SHIPPED = hydrate(manifest);

export function useChain() {
  const [state, setState] = useState<ChainState>({
    snapshot: SHIPPED,
    source: "snapshot",
    loading: false,
    error: null,
  });

  const refresh = useCallback(async () => {
    setState((s) => ({ ...s, loading: true, error: null }));
    try {
      const live = await loadChainSnapshot();
      // Settlement history needs archival log queries the public RPC won't
      // serve in one range, so keep the manifest's receipts and take the
      // live values for everything that actually moves.
      setState({
        snapshot: { ...live, settlements: live.settlements.length ? live.settlements : SHIPPED.settlements },
        source: "live",
        loading: false,
        error: null,
      });
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      setState((s) => ({
        ...s,
        loading: false,
        error: /request limit|rate limit|429|10,000/i.test(message)
          ? "Arc's public RPC is rate-limiting — still showing the verified snapshot."
          : message.split("\n")[0],
      }));
    }
  }, []);

  return { ...state, refresh };
}
